name: System Report

on:
  push:

jobs:
  system-info:
    runs-on: ubuntu-latest

    steps:
        - name: Print system information
          run: |
            echo "Operating System: $(uname -s)"
            echo "Kernel Version: $(uname -r)"
            # df -h / -> shows disk usage/free space for the root filesystem in a human-readable format.
            echo "Disk Usage: $(df -h)"
            echo "Date: $(date)"
        - name: Install tree
          run: |
            sudo apt-get update
            sudo apt-get install -y tree
    
        - name: Display runner home directory
          run: tree -L 2 "$HOME"

  tool-check:
    runs-on: ubuntu-latest

    steps:
        - name: Install jq
          run: |
            sudo apt-get update
            sudo apt-get install -y jq
        - name: Create reports.json
          run: |
            echo '{
            "project": "CI-CD Exercise",
            "status": "success",
            "environment": "GitHub Actions"
            }' > reports.json
        - name: Read value using jq
          run: |
            jq '.status' reports.json
            jq '.project' report.json